from __future__ import annotations

GENRE_CHOICES = (
    (
        'Fantasy',
        (
            ('Alternate History', 'Alternate History'),
            ("Children's Story", "Children's Story"),
            ('Comedy', 'Comedy'),
            ('Contemporary', 'Contemporary'),
            ('Dark Fantasy', 'Dark Fantasy'),
            ('Fairy Tale', 'Fairy Tale'),
            ('High Fantasy', 'High Fantasy'),
            ('Historical Fantasy', 'Historical Fantasy'),
            ('Low Fantasy', 'Low Fantasy'),
            ('Magical Realism', 'Magical Realism'),
            ('Mythic Fiction', 'Mythic Fiction'),
            ('Paranormal Fantasy', 'Paranormal Fantasy'),
            ('Sword and Sorcery', 'Sword and Sorcery'),
            ('Urban Fantasy', 'Urban Fantasy'),
        ),
    ),
    (
        'Horror',
        (
            ('Comedy Horror', 'Comedy Horror'),
            ('Dark Fantasy Horror', 'Dark Fantasy Horror'),
            ('Gothic Horror', 'Gothic Horror'),
            ('Historical Horror', 'Historical Horror'),
            ('Lovecraftian Horror', 'Lovecraftian Horror'),
            ('Occult Horror', 'Occult Horror'),
            ('Psychological Horror', 'Psychological Horror'),
            ('Science Fiction Horror', 'Science Fiction Horror'),
            ('Slasher', 'Slasher'),
            ('Supernatural Horror', 'Supernatural Horror'),
            ('Thriller Horror', 'Thriller Horror'),
            ('Zombie Horror', 'Zombie Horror'),
        ),
    ),
    (
        'Mystery',
        (
            ('Amateur Sleuth', 'Amateur Sleuth'),
            ('Cozy Mystery', 'Cozy Mystery'),
            ('Crime Fiction', 'Crime Fiction'),
            ('Detective Fiction', 'Detective Fiction'),
            ('Espionage', 'Espionage'),
            ('Hardboiled', 'Hardboiled'),
            ('Historical Mystery', 'Historical Mystery'),
            ('Legal Thriller', 'Legal Thriller'),
            ('Medical Thriller', 'Medical Thriller'),
            ('Noir', 'Noir'),
            ('Police Procedural', 'Police Procedural'),
            ('Private Investigator', 'Private Investigator'),
            ('Psychological Thriller', 'Psychological Thriller'),
            ('Romantic Suspense', 'Romantic Suspense'),
            ('Spy Fiction', 'Spy Fiction'),
            ('Supernatural Mystery', 'Supernatural Mystery'),
            ('Thriller', 'Thriller'),
        ),
    ),
    (
        'Romance',
        (
            ('Contemporary Romance', 'Contemporary Romance'),
            ('Erotic Romance', 'Erotic Romance'),
            ('Historical Romance', 'Historical Romance'),
            ('Inspirational Romance', 'Inspirational Romance'),
            ('LGBTQ+ Romance', 'LGBTQ+ Romance'),
            ('Paranormal Romance', 'Paranormal Romance'),
            ('Regency Romance', 'Regency Romance'),
            ('Romantic Comedy', 'Romantic Comedy'),
            ('Romantic Suspense', 'Romantic Suspense'),
            ('Science Fiction Romance', 'Science Fiction Romance'),
            ('Time Travel Romance', 'Time Travel Romance'),
            ('Western Romance', 'Western Romance'),
        ),
    ),
    (
        'Science Fiction',
        (
            ('Alternate History', 'Alternate History'),
            ('Apocalyptic', 'Apocalyptic'),
            ('Biopunk', 'Biopunk'),
            ('Cyberpunk', 'Cyberpunk'),
            ('Dystopian', 'Dystopian'),
            ('Hard Science Fiction', 'Hard Science Fiction'),
            ('Military Science Fiction', 'Military Science Fiction'),
            ('Post-Apocalyptic', 'Post-Apocalyptic'),
            ('Space Opera', 'Space Opera'),
            ('Steampunk', 'Steampunk'),
            ('Time Travel', 'Time Travel'),
            ('Utopian', 'Utopian'),
        ),
    ),
    (
        'Thriller and Suspense',
        (
            ('Action Thriller', 'Action Thriller'),
            ('Adventure Thriller', 'Adventure Thriller'),
            ('Crime Thriller', 'Crime Thriller'),
            ('Espionage Thriller', 'Espionage Thriller'),
            ('Medical Thriller', 'Medical Thriller'),
            ('Psychological Thriller', 'Psychological Thriller'),
            ('Romantic Suspense', 'Romantic Suspense'),
            ('Spy Thriller', 'Spy Thriller'),
            ('Supernatural Thriller', 'Supernatural Thriller'),
            ('Techno-thriller', 'Techno-thriller'),
            ('Legal Thriller', 'Legal Thriller'),
            ('Political Thriller', 'Political Thriller'),
        ),
    ),
    (
        'Western',
        (
            ('Contemporary Western', 'Contemporary Western'),
            ('Historical Western', 'Historical Western'),
            ('Romantic Western', 'Romantic Western'),
            ('Science Fiction Western', 'Science Fiction Western'),
            ('Steampunk Western', 'Steampunk Western'),
            ('Weird Western', 'Weird Western'),
        ),
    ),
    (
        'Adventure',
        (
            ('Action Adventure', 'Action Adventure'),
            ('Historical Adventure', 'Historical Adventure'),
            ('Romantic Adventure', 'Romantic Adventure'),
            ('Science Fiction Adventure', 'Science Fiction Adventure'),
            ('Steampunk Adventure', 'Steampunk Adventure'),
            ('Survival Adventure', 'Survival Adventure'),
            ('Thriller Adventure', 'Thriller Adventure'),
        ),
    ),
    (
        'Biography',
        (
            ('Autobiography', 'Autobiography'),
            ('Memoir', 'Memoir'),
            ('Biography', 'Biography'),
            ('Diary', 'Diary'),
            ('Letters', 'Letters'),
            ('Travelogue', 'Travelogue'),
        ),
    ),
    (
        "Children's Literature",
        (
            ('Picture Book', 'Picture Book'),
            ('Early Reader', 'Early Reader'),
            ('Chapter Book', 'Chapter Book'),
            ('Middle Grade', 'Middle Grade'),
            ('Young Adult', 'Young Adult'),
        ),
    ),
    (
        'Classics',
        (
            ('Ancient Classics', 'Ancient Classics'),
            ('Medieval Classics', 'Medieval Classics'),
            ('Renaissance Classics', 'Renaissance Classics'),
            ('18th Century Classics', '18th Century Classics'),
            ('19th Century Classics', '19th Century Classics'),
            ('20th Century Classics', '20th Century Classics'),
        ),
    ),
    (
        'Comics and Graphic Novels',
        (
            ('Superhero', 'Superhero'),
            ('Manga', 'Manga'),
            ('Graphic Memoir', 'Graphic Memoir'),
            ('Graphic Novel', 'Graphic Novel'),
            ('Webcomics', 'Webcomics'),
        ),
    ),
    (
        'Drama',
        (
            ('Comedy', 'Comedy'),
            ('Tragedy', 'Tragedy'),
            ('Historical Drama', 'Historical Drama'),
            ('Musical', 'Musical'),
            ('Opera', 'Opera'),
            ('Pantomime', 'Pantomime'),
            ('Radio Drama', 'Radio Drama'),
            ('Screenplay', 'Screenplay'),
            ('Television Script', 'Television Script'),
        ),
    ),
    (
        'Non-Fiction',
        (
            ('Biography', 'Biography'),
            ('Autobiography', 'Autobiography'),
            ('Memoir', 'Memoir'),
            ('Essay', 'Essay'),
            ('Journalism', 'Journalism'),
            ('Travel Writing', 'Travel Writing'),
            ('Self-help', 'Self-help'),
            ('Health and Wellness', 'Health and Wellness'),
            ('Cookbook', 'Cookbook'),
            ('Art and Photography', 'Art and Photography'),
            ('Music', 'Music'),
            ('Science', 'Science'),
            ('History', 'History'),
            ('Philosophy', 'Philosophy'),
            ('Psychology', 'Psychology'),
            ('Religion', 'Religion'),
            ('Politics', 'Politics'),
            ('Business', 'Business'),
            ('Economics', 'Economics'),
            ('Education', 'Education'),
            ('Law', 'Law'),
            ('Technology', 'Technology'),
            ('Environment', 'Environment'),
            ('Sports', 'Sports'),
        ),
    ),
)

LITERATURE_TYPE_CHOICES = (
    ('Paper', 'Paper'),
    ('Electronic', 'Electronic'),
    ('Audiobook', 'Audiobook'),
)

INSTRUMENT_CHOICES = [
    ('Guitar', 'Guitar'),
    ('Drums', 'Drums'),
    ('Piano', 'Piano'),
    ('Bass', 'Bass'),
    ('Violin', 'Violin'),
]
