# Generated by Django 5.1.1 on 2025-03-20 21:52
from __future__ import annotations

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(
                        max_length=128,
                        verbose_name='password',
                    ),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='last login',
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={
                            'unique': 'A user with that username already exists.',
                        },
                        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator(),
                        ],
                        verbose_name='username',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name='first name',
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name='last name',
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='date joined',
                    ),
                ),
                ('email', models.EmailField(max_length=254, unique=True)),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        related_name='customuser_groups',
                        to='auth.group',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        related_name='customuser_permissions',
                        to='auth.permission',
                    ),
                ),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'pronouns',
                    models.CharField(blank=True, default='', max_length=30),
                ),
                (
                    'avatar',
                    models.ImageField(blank=True, upload_to='users/avatars/'),
                ),
                (
                    'about',
                    models.CharField(blank=True, default='', max_length=250),
                ),
                (
                    'quote',
                    models.CharField(blank=True, default='', max_length=30),
                ),
                ('favour_points', models.IntegerField(default=0)),
                (
                    'instagram_link',
                    models.URLField(
                        blank=True,
                        default='',
                        max_length=100,
                    ),
                ),
                (
                    'telegram_link',
                    models.URLField(
                        blank=True,
                        default='',
                        max_length=100,
                    ),
                ),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                (
                    'follows',
                    models.ManyToManyField(
                        blank=True,
                        related_name='followers',
                        to='users.userprofile',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
