# Generated by Django 5.1.1 on 2025-03-20 22:24
from __future__ import annotations

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={
                'ordering': ['-joined_at'],
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_link',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_pronouns',
            field=models.CharField(
                blank=True,
                help_text='Specify your pronouns if not listed',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favour_points',
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(
                blank=True,
                choices=[
                    ('he', 'He/Him'),
                    ('she', 'She/Her'),
                    ('they', 'They/Them'),
                    ('ze', 'Ze/Zir'),
                    ('she_they', 'She/They'),
                    ('he_they', 'He/They'),
                    ('any', 'Any'),
                    ('none', 'None'),
                    ('other', 'Other'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
