# Generated by Django 5.1.1 on 2025-03-30 00:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Artist Profile',
                'verbose_name_plural': 'Artist Profiles',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('founded', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheatreCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TheatrePieceGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TheatreProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WriterGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to='user_profile.artistprofile')),
            ],
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='mediums',
            field=models.ManyToManyField(blank=True, to='user_profile.medium'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='styles',
            field=models.ManyToManyField(blank=True, to='user_profile.style'),
        ),
        migrations.CreateModel(
            name='TheatreArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('playwright', 'Playwright'), ('designer', 'Designer'), ('other', 'Other')], max_length=20)),
                ('theatre_companies', models.ManyToManyField(blank=True, to='user_profile.theatrecompany')),
                ('preferred_genre', models.ManyToManyField(blank=True, help_text="Theatre artist's preferred genre", to='user_profile.theatrepiecegenre')),
                ('current_projects', models.ManyToManyField(blank=True, to='user_profile.theatreproject')),
            ],
            options={
                'verbose_name': 'Theatre Artist Profile',
                'verbose_name_plural': 'Theatre Artist Profiles',
            },
        ),
        migrations.CreateModel(
            name='TheatreRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_roles', to='user_profile.theatreartistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('default', 'Default'), ('musician', 'Musician'), ('artist', 'Artist'), ('theatre', 'Theatre Artist'), ('writer', 'Writer'), ('craftsman', 'Craftsman')], default='default', max_length=20)),
                ('pronouns', models.CharField(blank=True, choices=[('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('ze', 'Ze/Zir'), ('she_they', 'She/They'), ('he_they', 'He/They'), ('any', 'Any'), ('none', 'None'), ('other', 'Other')], max_length=20, null=True)),
                ('custom_pronouns', models.CharField(blank=True, help_text='Specify your pronouns if not listed', max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='users/avatars/')),
                ('about', models.CharField(blank=True, default='', max_length=250)),
                ('quote', models.CharField(blank=True, default='', max_length=30)),
                ('favour_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followers', to='user_profile.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='theatreartistprofile',
            name='main_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre_artist_profiles', to='user_profile.userprofile'),
        ),
        migrations.CreateModel(
            name='MusicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bands', models.ManyToManyField(blank=True, to='user_profile.band')),
                ('genres', models.ManyToManyField(blank=True, to='user_profile.genre')),
                ('instruments', models.ManyToManyField(blank=True, to='user_profile.instrument')),
                ('main_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musician_profiles', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'Musician Profile',
                'verbose_name_plural': 'Musician Profiles',
            },
        ),
        migrations.CreateModel(
            name='CraftsmanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craft_type', models.CharField(choices=[('woodworking', 'Woodworking'), ('pottery', 'Pottery'), ('textiles', 'Textiles'), ('metalwork', 'Metalwork'), ('glassblowing', 'Glassblowing'), ('other', 'Other')], help_text='Preferred user type of craft', max_length=20)),
                ('materials', models.ManyToManyField(blank=True, to='user_profile.material')),
                ('main_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craftsman_profiles', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'Craftsman Profile',
                'verbose_name_plural': 'Craftsman Profiles',
            },
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='main_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profiles', to='user_profile.userprofile'),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='user_profile.craftsmanprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influences', models.CharField(blank=True, max_length=200)),
                ('genres', models.ManyToManyField(blank=True, to='user_profile.writergenre')),
                ('main_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_profiles', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': 'Writer Profile',
                'verbose_name_plural': 'Writer Profiles',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'platform')},
            },
        ),
        migrations.AddConstraint(
            model_name='theatreartistprofile',
            constraint=models.UniqueConstraint(fields=('main_profile',), name='unique_theatre_artist_profile'),
        ),
        migrations.AddConstraint(
            model_name='musicianprofile',
            constraint=models.UniqueConstraint(fields=('main_profile',), name='unique_musician_profile'),
        ),
        migrations.AddConstraint(
            model_name='craftsmanprofile',
            constraint=models.UniqueConstraint(fields=('main_profile',), name='unique_craftsman_profile'),
        ),
        migrations.AddConstraint(
            model_name='artistprofile',
            constraint=models.UniqueConstraint(fields=('main_profile',), name='unique_artist_profile'),
        ),
        migrations.AddConstraint(
            model_name='writerprofile',
            constraint=models.UniqueConstraint(fields=('main_profile',), name='unique_writer_profile'),
        ),
    ]
