# Generated by Django 5.1.1 on 2025-02-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, default='', max_length=250)),
                ('quote', models.CharField(blank=True, default='', max_length=30)),
                ('instagram_link', models.URLField(blank=True, default='', max_length=100)),
                ('telegram_link', models.URLField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
