# Generated by Django 5.1.3 on 2024-12-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChordA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('alternative', models.IntegerField(blank=True, null=True)),
                ('subset', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chords_a',
            },
        ),
        migrations.CreateModel(
            name='ChordB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('alternative', models.IntegerField(blank=True, null=True)),
                ('subset', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chords_b',
            },
        ),
        migrations.CreateModel(
            name='ChordC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('alternative', models.IntegerField(blank=True, null=True)),
                ('subset', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chords_c',
            },
        ),
        migrations.CreateModel(
            name='ChordD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('alternative', models.IntegerField(blank=True, null=True)),
                ('subset', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chords_d',
            },
        ),
        migrations.CreateModel(
            name='ChordE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('alternative', models.IntegerField(blank=True, null=True)),
                ('subset', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chords_e',
            },
        ),
        migrations.CreateModel(
            name='ChordF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('alternative', models.IntegerField(blank=True, null=True)),
                ('subset', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chords_f',
            },
        ),
        migrations.CreateModel(
            name='ChordG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('alternative', models.IntegerField(blank=True, null=True)),
                ('subset', models.IntegerField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chords_g',
            },
        ),
        migrations.CreateModel(
            name='ChordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('group', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chord_type',
            },
        ),
    ]
