# Generated by Django 5.1.1 on 2025-04-09 12:54

import api.v1.files.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.v1.files.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg', 'mp3', 'wav', 'ogg', 'flac', 'mp4', 'mov', 'avi', 'webm', 'pdf', 'doc', 'docx', 'txt', 'rtf', 'zip', 'rar'])])),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('visual_art', 'Visual Art'), ('music', 'Music'), ('writing', 'Writing'), ('theatre', 'Theatre'), ('crafts', 'Crafts'), ('other', 'Other')], default='other', max_length=100)),
                ('file_type', models.CharField(blank=True, choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('pdf', 'PDF'), ('other', 'Other')], max_length=50, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CraftsModel',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filemodel')),
                ('materials', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=50)),
                ('time_required', models.CharField(blank=True, max_length=100)),
                ('tools_required', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
            ],
            bases=('files.filemodel',),
        ),
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filemodel')),
                ('cover_art', models.ImageField(blank=True, upload_to=api.v1.files.models.get_cover_art_upload_path)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('instruments', models.CharField(blank=True, max_length=255)),
                ('lyrics', models.TextField(blank=True)),
                ('composer', models.CharField(blank=True, max_length=100)),
                ('recording_date', models.DateField(blank=True, null=True)),
            ],
            bases=('files.filemodel',),
        ),
        migrations.CreateModel(
            name='TheatreModel',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filemodel')),
                ('playwright', models.CharField(blank=True, max_length=100)),
                ('performance_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cast_size', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('theme', models.CharField(blank=True, max_length=100)),
            ],
            bases=('files.filemodel',),
        ),
        migrations.CreateModel(
            name='VisualArtModel',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filemodel')),
                ('style', models.CharField(blank=True, max_length=100)),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('dimensions_physical', models.CharField(blank=True, help_text="Physical dimensions (e.g. '24x36 inches')", max_length=100)),
                ('creation_date', models.DateField(blank=True, null=True)),
            ],
            bases=('files.filemodel',),
        ),
        migrations.CreateModel(
            name='WritingModel',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filemodel')),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100)),
            ],
            bases=('files.filemodel',),
        ),
    ]
