# Generated by Django 5.1.3 on 2024-12-26 00:09

import api.v1.files.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subgenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WriterLiteratureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literature_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to=api.v1.files.models.get_upload_path)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('style', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('height_px', models.PositiveIntegerField(default=0)),
                ('width_px', models.PositiveIntegerField(default=0)),
                ('height_cm', models.PositiveIntegerField(default=0)),
                ('width_cm', models.PositiveIntegerField(default=0)),
                ('authors', models.ManyToManyField(related_name='%(app_label)s_%(class)s_authors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-style'],
            },
        ),
        migrations.CreateModel(
            name='MusicianFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to=api.v1.files.models.get_upload_path)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(max_length=100)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('mood', models.CharField(max_length=100)),
                ('duration', models.TimeField()),
                ('bpm', models.PositiveIntegerField(default=0)),
                ('authors', models.ManyToManyField(related_name='%(app_label)s_%(class)s_authors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instruments', models.ManyToManyField(blank=True, to='files.musicianinstruments')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WriterGenreTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('subgenres', models.ManyToManyField(to='files.subgenre')),
            ],
        ),
        migrations.CreateModel(
            name='WriterFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to=api.v1.files.models.get_upload_path)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(related_name='%(app_label)s_%(class)s_authors', to=settings.AUTH_USER_MODEL)),
                ('subgenre', models.ManyToManyField(to='files.subgenre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(to='files.writergenretypes')),
                ('literature_type', models.ManyToManyField(to='files.writerliteraturetype')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
