# Generated by Django 5.1.1 on 2025-02-27 14:26

import apps.v1.files.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.v1.files.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp3', 'wav', 'pdf', 'doc', 'docx'])])),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('file_type', models.CharField(blank=True, choices=[('image', 'Image'), ('audio', 'Audio'), ('document', 'Document'), ('pdf', 'PDF'), ('other', 'Other')], max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloadable', models.BooleanField(default=False)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFileModel',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filemodel')),
                ('word_count', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=100)),
            ],
            bases=('files.filemodel',),
        ),
        migrations.CreateModel(
            name='ImageFileModel',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filemodel')),
                ('style', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('height_px', models.PositiveIntegerField()),
                ('width_px', models.PositiveIntegerField()),
            ],
            bases=('files.filemodel',),
        ),
        migrations.CreateModel(
            name='MusicFileModel',
            fields=[
                ('filemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.filemodel')),
                ('genre', models.CharField(max_length=100)),
                ('bpm', models.PositiveIntegerField()),
            ],
            bases=('files.filemodel',),
        ),
    ]
